### ISSUE TITLE
MVP Site needs to revalidate OKTA Token

### ISSUE THREAD

**Issue by robearlam** [Sitecore/XM-Cloud-Introduction#174]
The MVP site needs to revalidate the Okta token periodically to ensure that users are correctly logged out on expiry.

This will match the functionality in the Applications API.

**Comment by jermdavis** [comment]
![image](https://user-images.githubusercontent.com/7868341/199450619-1955c6ac-9d7a-4312-a86b-ab03f9d0ec97.png)

I want to upvote this issue for fixing for next year's application. If (like me) you're not very fast at filling in the form and have a chunk of stuff to submit, then this issue will happen.  And when it does you lose whatever entry you had just typed in, and have to re-do it. And that's frustrating.

But ideally I don't think the fix is "make the website log you out in the same way as the API". I'd argue posting an entry should be a mark that your session is active, and it should do whatever's needed to refresh tokens. Hence preventing you from getting logged out by either the website or the API while you're actively working on submissions. Fine for it to time you out if you do nothing for half an hour. But it's annoying if it times you out when you'd done something every 5-10 mins during that half hour...

Not sure how practical that is - but I think it would be a significant usability improvement for people with a chunk of stuff to submit.
