### ISSUE TITLE
It is currently possible to navigate to secure pages

### ISSUE THREAD

**Issue by robearlam** [Sitecore/XM-Cloud-Introduction#189]
Currently, you can directly navigate to secure pages when unauthenticated, if you know the URL.

When unauthenticated secure URL's should return a 404 response.

**Comment by sc-ivanlieckens** [comment]
@robearlam A 404 is misleading and there was a direct link being shared to the Application page for MVP candidates causing them to see a 404 causing confusion. A 401 should be returned to ensure the Authentication mechanism kicks in instead prompting login... The issue is that this also means you should take care of a system to redirect to the original page target afterwards since Okta always returns to the homepage currently...
