### ISSUE TITLE
a Windows version 10.0.20348-based image is incompatible with a 10.0.19044 host

### ISSUE THREAD

**Issue by Hemanth089** [Sitecore/XM-Cloud-Introduction#240]
**Describe the bug**
Following local setup instruction. But getting this error.

**To Reproduce**
1. RUN '.\init.ps1 -InitEnv -LicenseXmlPath "C:\path\to\license.xml" -AdminPassword "DesiredAdminPassword"'
2. RUN '.\up.ps1'

**Expected behavior**
Dockers should run successfully and able to access XM cloud locally.

**Screenshots**
![XM Cloud Error](https://user-images.githubusercontent.com/7092837/222772639-df8cf765-cf70-412c-92ad-08de0c4fcc3a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by robearlam** [comment]
As per the Wiki, the intention is for repository to run the latest base image versions possible. If you have a lower version of windows it is your responsibilty to update the `.env` so that you can run locally.

https://github.com/Sitecore/XM-Cloud-Introduction/wiki/Changing-local-Docker-Image-Base-OS-Versions
